version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # example for FastAPI
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # prevent host-node_modules conflict
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev   # use dev server with hot reload
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
